name: "Mirroring Repository"
description: "Mirror a repository to another repository on GitHub, GitLab, BitBucket, AWS CodeCommit, etc."
branding:
  icon: "archive"
  color: "blue"
inputs:
  github_username:
    description: "your github username"
    required: true
  access_token:
    description: "personal access token for the target repository"
    required: true
  target_repo:
    description: "Target repository, like username/reponame"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
